CREATE DATABASE THAT HOLDS BURGER INFORMATION 
CREATE DATABASE burgers_db;

USE burgers_db;

CREATE TABLE burgers
(
    id INTEGER (10)
    AUTO_INCREMENT, 
    burger_name VARCHAR
    (100) NOT NULL, 
    devoured BOOLEAN DAFAULT false NOT NULL, 
    PRIMARY KEY
    (id)
);